version: '3'
services:
  search:
    image: getmeili/meilisearch
    ports:
      - 7700:7700
    environment:
      MEILI_MASTER_KEY: shithouse123456789

  minio:
    image: quay.io/minio/minio:latest
    command: minio server /home/shared --console-address "0.0.0.0:9001" --address "0.0.0.0:9000"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ${PWD}/data:/home/shared
    environment:
      MINIO_ROOT_USER: shithouse
      MINIO_ROOT_PASSWORD: shithouse
      MINIO_DEFAULT_BUCKETS: shithouse


  # db:
  #   image: postgres:16
  #   environment:
  #     - POSTGRES_PASSWORD=mysecretpassword

  shithouse:
    build: .
    ports:
      - 8001:8000
