# Generated by Django 5.0.6 on 2024-06-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("default", "0001_initial"),
        ("house", "0002_address_agents"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="images",
            field=models.ManyToManyField(to="default.image"),
        ),
    ]
