# Generated by Django 5.0.6 on 2024-06-14 06:58

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_feature", models.BooleanField(default=False)),
                (
                    "avatar_thumbnail",
                    imagekit.models.fields.ProcessedImageField(upload_to="images"),
                ),
            ],
        ),
    ]
