# Generated by Django 5.0.6 on 2024-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("default", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="avatar_thumbnail",
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
