# Generated by Django 5.0.6 on 2024-06-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
        ("default", "0002_remove_image_avatar_thumbnail_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="feature_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="default.image",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="feature_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="default.image",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="feature_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="default.image",
            ),
        ),
    ]
